import sys

sys.path.append("../colmap-manage/")

from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager

data_folder_path = "/home/chli/chLi/Dataset/NeRF/3vjia_simple/"
video_file_path = "None"
down_sample_scale = 4

scale = 1
show_image = False
print_progress = True
remove_old = False
remain_db = True
valid_percentage = 0.8
dataset_folder_path = "../colmap-manage/output/3vjia_simple/"
method_dict = {
    "max_d": 192,
    "interval_scale": 1.06,
}

COLMAPManager(data_folder_path, video_file_path).autoGenerateData(
    remove_old, remain_db, valid_percentage
)
DatasetManager().generateDataset(
    "mvs", data_folder_path, dataset_folder_path, method_dict, print_progress
)
